server:
  port: 9091

spring:
  application:
    name: coupon-gateway
eureka:
  client:
    service-url:
      # 注册到eureka server
      defaultZone: http://server1:9090/eureka/
zuul:
  prefix: /coupon
  routes:
    # 优惠券模板微服务路由配置定义
    template:
      path: /template/**
      serviceId: coupon-template
      strip-prefix: false
  host:
    #超时时间
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

#负载均衡
ribbon:
  #超时时间
  ConnectTimeout: 15000
  ReadTimeout: 15000