server:
  port: 9091

spring:
  application:
    name: coupon-gateway
eureka:
  client:
    service-url:
      defaultZone: http://server1:${server.port}/eureka/
zuul:
  prefix: /coupon
  routes:
    # 优惠券模板微服务路由配置定义
    template:
      path: /template/**
      serviceId: coupon-template
      strip-prefix: false
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 15000